package apidocs

import (
	"net/http"

	_ "community-backend/docs"
	httpSwagger "github.com/swaggo/http-swagger/v2"
	"github.com/swaggo/swag"
)

// RegisterRoutes registers the documentation endpoints
func RegisterRoutes(mux *http.ServeMux) {
	// 1. Raw OpenAPI JSON specification (Dynamically generated by Swag)
	mux.HandleFunc("/docs/openapi.json", func(w http.ResponseWriter, r *http.Request) {
		doc, err := swag.ReadDoc()
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(doc))
	})

	// 2. Modern Scalar API Documentation Portal (Available at /docs)
	mux.HandleFunc("/docs", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(scalarHTML))
	})

	// 3. Official Swagger UI (Available at /swagger/)
	mux.HandleFunc("/swagger/", httpSwagger.WrapHandler)
}

const scalarHTML = `<!doctype html>
<html>
  <head>
    <title>Farm Community & GAP API Documentation</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/svg+xml" href="https://scalar.com/favicon.svg">
    <style>body { margin: 0; }</style>
  </head>
  <body>
    <script
      id="api-reference"
      data-url="/docs/openapi.json">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>`
